"""Searchable gallery categories: detector (COCO) labels, ImageNet-21k WordNet subtrees, Open Images labels for evaluation."""

def C(key, name, group, words='', det=(), wn=(), wn_not=(), oi=(), oi_not=()):
    return dict(key=key, name=name, group=group, words=[w.strip() for w in words.split(',') if w.strip()],
                det=list(det), wn=list(wn), wn_not=list(wn_not), oi=list(oi), oi_not=list(oi_not))

CATS = [
    # People (detector only: the classifier's person classes are never used)
    C('people', 'People', 'People', 'person,people,human,humans,man,men,woman,women,kid,kids,friends,family',
      det=['person'], oi=['Person', 'Man', 'Woman', 'Child', 'Boy', 'Girl']),
    # Animals
    C('dog', 'Dogs', 'Animals', 'dog,dogs,puppy,puppies,pup,doggy,doggo,canine', det=['dog'], wn=['n02084071'], oi=['Dog', 'Puppy']),
    C('cat', 'Cats', 'Animals', 'cat,cats,kitten,kittens,kitty,feline', det=['cat'], wn=['n02121808'], oi=['Cat', 'Kitten']),
    C('bird', 'Birds', 'Animals', 'bird,birds,parrot,pigeon,seagull,duck,chicken', det=['bird'], wn=['n01503061'], oi=['Bird', 'Duck', 'Chicken']),
    C('horse', 'Horses', 'Animals', 'horse,horses,pony,ponies', det=['horse'], wn=['n02374451'], oi=['Horse']),
    C('fish', 'Fish', 'Animals', 'fish,fishes,aquarium', wn=['n02512053'], oi=['Fish']),
    C('insect', 'Insects', 'Animals', 'insect,insects,bug,bugs,bee,ladybug,beetle,dragonfly', wn=['n02159955'], wn_not=['n02274259'], oi=['Insect']),
    C('butterfly', 'Butterflies', 'Animals', 'butterfly,butterflies,moth', wn=['n02274259'], oi=['Butterfly']),
    C('cow', 'Cows', 'Animals', 'cow,cows,cattle,bull,calf,ox', det=['cow'], wn=['n02402425'], oi=['Cattle']),
    C('sheep', 'Sheep', 'Animals', 'sheep,lamb,lambs', det=['sheep'], wn=['n02411705'], oi=['Sheep']),
    C('goat', 'Goats', 'Animals', 'goat,goats', wn=['n02416519'], oi=['Goat']),
    C('pig', 'Pigs', 'Animals', 'pig,pigs,piglet,hog', wn=['n02395406'], oi=['Pig']),
    C('elephant', 'Elephants', 'Animals', 'elephant,elephants', det=['elephant'], wn=['n02503517'], oi=['Elephant']),
    C('bear', 'Bears', 'Animals', 'bear,bears', det=['bear'], wn=['n02131653'], oi=['Bear']),
    C('zebra', 'Zebras', 'Animals', 'zebra,zebras', det=['zebra'], wn=['n02391049'], oi=['Zebra']),
    C('giraffe', 'Giraffes', 'Animals', 'giraffe,giraffes', det=['giraffe'], wn=['n02439033'], oi=['Giraffe']),
    C('monkey', 'Monkeys', 'Animals', 'monkey,monkeys,ape,apes,gorilla,chimpanzee', wn=['n02484322', 'n02470325'], oi=['Monkey']),
    C('lion', 'Lions', 'Animals', 'lion,lions', wn=['n02129165'], oi=['Lion']),
    C('tiger', 'Tigers', 'Animals', 'tiger,tigers', wn=['n02129604'], oi=['Tiger']),
    C('rabbit', 'Rabbits', 'Animals', 'rabbit,rabbits,bunny,bunnies,hare', wn=['n02324045'], oi=['Rabbit']),
    C('reptile', 'Reptiles', 'Animals', 'reptile,reptiles,lizard,snake,snakes,turtle,turtles,tortoise,crocodile', wn=['n01661091'], oi=['Reptile', 'Snake', 'Turtle']),
    C('animal', 'Animals', 'Animals', 'animal,animals,wildlife,pet,pets',
      det=['dog', 'cat', 'bird', 'horse', 'sheep', 'cow', 'elephant', 'bear', 'zebra', 'giraffe'], wn=['n00015388'], oi=['Animal', 'Pet']),
    # Vehicles
    C('car', 'Cars', 'Vehicles', 'car,cars,auto,automobile,vehicle', det=['car'], wn=['n02958343'], oi=['Car']),
    C('truck', 'Trucks', 'Vehicles', 'truck,trucks,lorry,pickup', det=['truck'], wn=['n04490091'], oi=['Truck']),
    C('bus', 'Buses', 'Vehicles', 'bus,buses,coach', det=['bus'], wn=['n02924116'], oi=['Bus']),
    C('motorcycle', 'Motorcycles', 'Vehicles', 'motorcycle,motorcycles,motorbike,scooter,moped', det=['motorcycle'],
      wn=['n03790512', 'n03791053', 'n03785016'], oi=['Motorcycle']),
    C('bicycle', 'Bicycles', 'Vehicles', 'bicycle,bicycles,bike,bikes,cycling', det=['bicycle'], wn=['n02834778'], oi=['Bicycle']),
    C('train', 'Trains', 'Vehicles', 'train,trains,railway,locomotive,tram,subway', det=['train'],
      wn=['n04468005', 'n03684823', 'n04335435', 'n03895866'], oi=['Train']),
    C('airplane', 'Airplanes', 'Vehicles', 'airplane,airplanes,plane,planes,aeroplane,aircraft,jet', det=['airplane'],
      wn=['n02691156'], oi=['Airplane']),
    C('helicopter', 'Helicopters', 'Vehicles', 'helicopter,helicopters', wn=['n03512147'], oi=['Helicopter']),
    C('boat', 'Boats', 'Vehicles', 'boat,boats,ship,ships,yacht,sailboat,ferry,canoe,kayak', det=['boat'],
      wn=['n02858304', 'n04194289', 'n04530566'], oi=['Boat', 'Ship']),
    # Food and drink
    C('food', 'Food', 'Food', 'food,meal,dish,dinner,lunch,breakfast,eating',
      det=['banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot dog', 'pizza', 'donut', 'cake'],
      wn=['n07557434', 'n07573696', 'n07622061', 'n07609840', 'n07705931', 'n07707451', 'n07612632', 'n07597365', 'n07850329', 'n07695965', 'n07583197'],
      oi=['Food', 'Fast food', 'Baked goods', 'Dessert']),
    C('pizza', 'Pizza', 'Food', 'pizza,pizzas', det=['pizza'], wn=['n07873807'], oi=['Pizza']),
    C('cake', 'Cakes', 'Food', 'cake,cakes,birthday cake,cupcake', det=['cake'], wn=['n07628870'], oi=['Cake']),
    C('burger', 'Burgers', 'Food', 'burger,burgers,hamburger,cheeseburger', wn=['n07697100'], oi=['Hamburger']),
    C('sushi', 'Sushi', 'Food', 'sushi', wn=['n07879450'], oi=['Sushi']),
    C('icecream', 'Ice cream', 'Food', 'ice cream,icecream,gelato,sundae', wn=['n07614500'], oi=['Ice cream']),
    C('fruit', 'Fruit', 'Food', 'fruit,fruits,banana,apple,orange,strawberry,grapes', det=['banana', 'apple', 'orange'], wn=['n07705931'], oi=['Fruit']),
    C('vegetable', 'Vegetables', 'Food', 'vegetable,vegetables,veggies,salad,broccoli,carrot', det=['broccoli', 'carrot'], wn=['n07707451'], oi=['Vegetable']),
    C('salad', 'Salads', 'Food', 'salad,salads', wn=['n07806221'], oi=['Salad']),
    C('dessert', 'Desserts', 'Food', 'dessert,desserts,sweets,pastry,cookies,chocolate,donut', det=['donut', 'cake'],
      wn=['n07609840', 'n07628870', 'n07597365', 'n07611358'], oi=['Dessert']),
    C('bread', 'Bread', 'Food', 'bread,baguette,toast,bun,croissant', wn=['n07679356'], oi=['Bread']),
    C('coffee', 'Coffee', 'Food', 'coffee,espresso,cappuccino,latte', wn=['n07929519'], oi=['Coffee', 'Coffee cup']),
    C('drink', 'Drinks', 'Food', 'drink,drinks,beverage,juice,tea,soda', wn=['n07881800'], oi=['Drink']),
    C('wine', 'Wine', 'Food', 'wine,red wine,white wine', wn=['n07891726'], oi=['Wine']),
    C('beer', 'Beer', 'Food', 'beer,beers,lager', wn=['n07886849'], oi=['Beer']),
    C('cocktail', 'Cocktails', 'Food', 'cocktail,cocktails,mojito,margarita', wn=['n07911677'], oi=['Cocktail']),
    # Nature
    C('beach', 'Beach', 'Nature', 'beach,beaches,seaside,shore,coast,sand', wn=['n09217230', 'n09428293', 'n09447666', 'n09428628', 'n08596076', 'n09421951', 'n09421799'], oi=['Beach']),
    C('sea', 'Sea', 'Nature', 'sea,ocean,waves,seascape', wn=['n09376198'], oi=['Sea', 'Ocean']),
    C('mountain', 'Mountains', 'Nature', 'mountain,mountains,peak,alps,hills,volcano', wn=['n09359803', 'n09193705', 'n09472597', 'n09303008'], oi=['Mountain']),
    C('lake', 'Lakes', 'Nature', 'lake,lakes,pond', wn=['n09332890', 'n09331251'], oi=['Lake']),
    C('river', 'Rivers', 'Nature', 'river,rivers,stream,creek', wn=['n09415584'], oi=['River']),
    C('waterfall', 'Waterfalls', 'Nature', 'waterfall,waterfalls,falls', oi=['Waterfall']),
    C('forest', 'Forest', 'Nature', 'forest,woods,jungle', wn=['n09411189'], oi=['Forest']),
    C('tree', 'Trees', 'Nature', 'tree,trees,palm tree', wn=['n13104059'], oi=['Tree']),
    C('flower', 'Flowers', 'Nature', 'flower,flowers,rose,roses,tulip,sunflower,bouquet,blossom', wn=['n11669921', 'n02879087'], oi=['Flower']),
    C('plant', 'Plants', 'Nature', 'plant,plants,houseplant,cactus,succulent', det=['potted plant'], wn=['n13083023'], oi=['Houseplant', 'Plant']),
    C('snow', 'Snow', 'Nature', 'snow,snowy,winter,skiing,ski,snowboard',
      wn=['n11508382', 'n09439032', 'n09436444', 'n00440747', 'n04251701', 'n04252077', 'n04252225', 'n04251791',
          'n00447073', 'n09438940', 'n03948242', 'n03218198', 'n00447221'], oi=['Snow']),
    C('sky', 'Sky', 'Nature', 'sky,clouds,cloud,blue sky', wn=['n09436708', 'n09247410', 'n09462600', 'n11487732', 'n09251407', 'n09444783'], oi=['Sky', 'Cloud']),
    C('sunset', 'Sunsets', 'Nature', 'sunset,sunsets,sunrise,dusk,dawn,golden hour', oi=['Sunset', 'Sunrise', 'Dusk', 'Afterglow']),
    C('night', 'Night', 'Nature', 'night,nighttime,night sky,stars', oi=['Night']),
    C('desert', 'Desert', 'Nature', 'desert,dunes,sand dunes', wn=['n09270735'], oi=['Desert']),
    C('grass', 'Grass & fields', 'Nature', 'grass,lawn,field,fields,meadow', wn=['n12102133', 'n09393605'], oi=['Grass', 'Meadow', 'Field']),
    C('rock', 'Rocks & cliffs', 'Nature', 'rock,rocks,cliff,cliffs,canyon,cave', wn=['n09246464', 'n09233446', 'n09238926', 'n09416076'], oi=['Rock', 'Cliff']),
    # Places
    C('city', 'City', 'Places', 'city,cities,downtown,skyline,cityscape,urban', wn=['n08524735', 'n08539072', 'n04233124', 'n03036149'], oi=['City', 'Cityscape']),
    C('building', 'Buildings', 'Places', 'building,buildings,architecture,house,houses', wn=['n02913152'], oi=['Building', 'House', 'Skyscraper']),
    C('skyscraper', 'Skyscrapers', 'Places', 'skyscraper,skyscrapers,tower block', wn=['n04233124'], oi=['Skyscraper']),
    C('church', 'Churches', 'Places', 'church,churches,cathedral,chapel,mosque,temple',
      wn=['n03028079', 'n02984061', 'n02984203', 'n03788195', 'n04407435'], oi=['Church']),
    C('castle', 'Castles', 'Places', 'castle,castles,palace,fortress', wn=['n02980441', 'n03878066', 'n03877845'], oi=['Castle']),
    C('bridge', 'Bridges', 'Places', 'bridge,bridges', wn=['n02898711'], oi=['Bridge']),
    C('street', 'Streets', 'Places', 'street,streets,road,roads,highway', wn=['n04334599', 'n04335209', 'n04096066'], oi=['Street', 'Road']),
    C('pool', 'Swimming pools', 'Places', 'pool,swimming pool,swimming', oi=['Swimming pool']),
    C('kitchen', 'Kitchens', 'Places', 'kitchen,kitchens', wn=['n03619890'], oi=['Kitchen']),
    C('bedroom', 'Bedrooms', 'Places', 'bedroom,bedrooms', wn=['n02821627'], oi=['Bedroom']),
    C('bathroom', 'Bathrooms', 'Places', 'bathroom,bathrooms,toilet', det=['toilet'], wn=['n02807731'], oi=['Bathroom']),
    C('livingroom', 'Living rooms', 'Places', 'living room,lounge', wn=['n03679712'], oi=['Living room']),
    C('restaurant', 'Restaurants', 'Places', 'restaurant,restaurants,cafe,bar,diner', wn=['n04081281'], oi=['Restaurant']),
    C('stadium', 'Stadiums', 'Places', 'stadium,arena', wn=['n04295881'], oi=['Stadium']),
    C('statue', 'Statues', 'Places', 'statue,statues,sculpture,monument', wn=['n04306847', 'n03743902'], oi=['Statue', 'Monument']),
    C('tower', 'Towers', 'Places', 'tower,towers', wn=['n04460130'], oi=['Tower']),
    C('lighthouse', 'Lighthouses', 'Places', 'lighthouse,lighthouses', wn=['n02814860'], oi=['Lighthouse']),
    C('fountain', 'Fountains', 'Places', 'fountain,fountains', wn=['n03388043'], oi=['Fountain']),
    # Events and activities
    C('fireworks', 'Fireworks', 'Events', 'fireworks,firework', oi=['Fireworks']),
    C('christmas', 'Christmas', 'Events', 'christmas,christmas tree,xmas', oi=['Christmas tree']),
    C('wedding', 'Weddings', 'Events', 'wedding,weddings,bride,groom', wn=['n08256735', 'n02898585'], oi=['Wedding']),
    C('birthday', 'Birthdays', 'Events', 'birthday,birthday party,candles', oi=['Birthday']),
    C('concert', 'Concerts', 'Events', 'concert,concerts,gig,festival,stage', wn=['n06892775'], oi=['Concert']),
    C('soccer', 'Football', 'Sports', 'football,soccer', wn=['n00478262', 'n04254680'], oi=['Football', 'Soccer']),
    C('basketball', 'Basketball', 'Sports', 'basketball', wn=['n00480993', 'n02802426'], oi=['Basketball (Sport)']),
    C('tennis', 'Tennis', 'Sports', 'tennis', det=['tennis racket'], wn=['n00482298'], oi=['Tennis']),
    C('skiing', 'Skiing', 'Sports', 'skiing,ski,skis,snowboarding', det=['skis', 'snowboard'], wn=['n00440747', 'n09436444'], oi=['Skiing']),
    C('surfing', 'Surfing', 'Sports', 'surfing,surf,surfboard', det=['surfboard'], wn=['n00445055'], oi=['Surfing']),
    C('swimming', 'Swimming', 'Sports', 'swimming,swim', wn=['n00442115'], oi=['Swimming']),
    # Things
    C('document', 'Documents', 'Things', 'document,documents,paper,papers,receipt,text,letter,page',
      wn=['n06470073', 'n03822171', 'n06595351', 'n07565083'], oi=['Document', 'Text']),
    C('book', 'Books', 'Things', 'book,books,reading', det=['book'], wn=['n02870526'], oi=['Book']),
    C('phone', 'Phones', 'Things', 'phone,phones,smartphone,mobile,cellphone,iphone', det=['cell phone'], wn=['n02992529'], oi=['Mobile phone']),
    C('computer', 'Computers', 'Things', 'computer,computers,laptop,laptops,pc,monitor,keyboard', det=['laptop', 'keyboard', 'mouse'],
      wn=['n03082979', 'n03642806', 'n03085602'], oi=['Laptop', 'Computer monitor']),
    C('tv', 'TVs', 'Things', 'tv,television,tvs,screen', det=['tv'], wn=['n04405907'], oi=['Television']),
    C('shoe', 'Shoes', 'Things', 'shoe,shoes,sneakers,boots,footwear,heels', wn=['n03380867', 'n03381126'], oi=['Shoe', 'Footwear']),
    C('glasses', 'Glasses', 'Things', 'glasses,eyeglasses,spectacles,sunglasses,shades', wn=['n04272054', 'n04356056'], oi=['Glasses', 'Sunglasses']),
    C('hat', 'Hats', 'Things', 'hat,hats,cap,caps', wn=['n03497657'], oi=['Hat']),
    C('watch', 'Watches', 'Things', 'watch,watches,wristwatch', wn=['n04555897'], oi=['Watch']),
    C('bag', 'Bags', 'Things', 'bag,bags,handbag,purse,backpack,suitcase,luggage', det=['backpack', 'handbag', 'suitcase'],
      wn=['n02774152', 'n02769748', 'n02773838'], oi=['Handbag', 'Backpack']),
    C('toy', 'Toys', 'Things', 'toy,toys,teddy bear,lego,doll', det=['teddy bear'], wn=['n03964744'], oi=['Toy', 'Teddy bear']),
    C('furniture', 'Furniture', 'Things', 'furniture,chair,chairs,sofa,couch,table,bed', det=['chair', 'couch', 'bed', 'dining table'],
      wn=['n03405725'], oi=['Furniture']),
    C('sofa', 'Sofas', 'Things', 'sofa,sofas,couch,couches', det=['couch'], wn=['n04256520'], oi=['Couch']),
    C('bed', 'Beds', 'Things', 'bed,beds', det=['bed'], wn=['n02818832'], oi=['Bed']),
    C('clock', 'Clocks', 'Things', 'clock,clocks', det=['clock'], wn=['n03046257'], oi=['Clock']),
    C('cup', 'Cups & mugs', 'Things', 'cup,cups,mug,mugs', det=['cup'], wn=['n03147509', 'n03797390'], oi=['Mug', 'Coffee cup']),
    C('bottle', 'Bottles', 'Things', 'bottle,bottles', det=['bottle'], wn=['n02876657'], oi=['Bottle']),
    C('umbrella', 'Umbrellas', 'Things', 'umbrella,umbrellas', det=['umbrella'], wn=['n04507155'], oi=['Umbrella']),
    C('guitar', 'Guitars', 'Things', 'guitar,guitars', wn=['n03467517'], oi=['Guitar']),
    C('piano', 'Pianos', 'Things', 'piano,pianos,keyboard', wn=['n03928116'], oi=['Piano']),
    C('instrument', 'Music', 'Things', 'music,musical instrument,instruments,drums,violin,guitar,piano', wn=['n03800933'], oi=['Musical instrument']),
]
