package com.localmediatools.tools

import com.localmediatools.core.OutputArea

enum class ToolSection(val title: String, val subtitle: String) {
    STACKS("Stacks", "Run several tools in a row"),
    EDIT("Edit & AI", "Retouch, cut out and anonymise with on-device AI"),
    IMAGES("Images", "Compress, convert, combine and brand photos"),
    VIDEO("Video", "Trim, cut, repackage and shrink videos"),
    GIF("GIF", "Create and slim down animations"),
    DOCUMENTS("PDF", "Pages, scans and merges"),
    PRINT("Print", "Photos and documents on your Wi-Fi printer"),
    PRIVACY("Privacy & audio", "Clean metadata and extract sound"),
}

enum class ToolId(
    val section: ToolSection,
    val title: String,
    val shortDescription: String,
    val longDescription: String,
    val area: OutputArea,
    /** Tools that save images and videos to different places. */
    val videoArea: OutputArea? = null,
) {
    TOOL_STACK(ToolSection.STACKS, "Tool stack", "Chain tools: each works on the last one's results",
        "Pick files once, add the tools you want in order — for example Blur faces → Video compressor → Video → GIF → GIF optimizer — and run them all with one tap. Each tool keeps all its settings; only the final results are saved.",
        OutputArea.EDITED),
    PHOTO_EDITOR(ToolSection.EDIT, "Photo editor", "Crop, straighten, light, colour and looks",
        "Crop and straighten, fine-tune light and colour, apply looks, then save a full-resolution copy. Your original stays untouched.",
        OutputArea.EDITED),
    MAGIC_ERASER(ToolSection.EDIT, "Magic eraser", "Brush away people and objects with AI",
        "Brush over what you don't want and an AI model running on this phone fills the gap with matching background. Nothing is uploaded.",
        OutputArea.EDITED),
    BLUR_REDACT(ToolSection.EDIT, "Blur & pixelate", "Hide faces, plates and private details",
        "Paint over faces, number plates, addresses or screens to blur or pixelate them before you share a photo.",
        OutputArea.EDITED),
    BACKGROUND_REMOVER(ToolSection.EDIT, "Background remover", "Cut out the subject as a transparent PNG",
        "An AI model on this phone finds the main subject (people, pets, products, objects) and removes everything behind it. Save as a transparent PNG or on a plain colour.",
        OutputArea.CUTOUTS),
    AUTO_ENHANCE(ToolSection.EDIT, "Auto enhance", "One tap: light, colour and detail by AI",
        "On-device AI recognises faces and the kind of scene (food, landscape, night, documents…) and fixes exposure, contrast, colour casts and sharpness to suit. Works on a whole batch.",
        OutputArea.ENHANCED),
    FACE_BLUR(ToolSection.EDIT, "Blur faces", "Find faces in photos and videos, pick who to hide",
        "On-device AI finds every face in your photos and videos and groups them by person. Choose who to blur or pixelate; faces are followed through the whole video.",
        OutputArea.BLURRED_IMAGES, OutputArea.BLURRED_VIDEO),

    SPLIT_VIDEO(ToolSection.VIDEO, "Split videos", "Cut into equal-length parts without re-encoding",
        "Divides each video into consecutive segments of the length you choose. Streams are copied, not re-encoded, so every part keeps the original quality.",
        OutputArea.SPLITS),
    TRIM_VIDEO(ToolSection.VIDEO, "Trim & rotate video", "Cut the start and end, fix sideways videos",
        "Keeps only the part you choose and can turn the video by 90° steps. Streams are copied, not re-encoded, so quality is untouched; the start snaps to the nearest earlier keyframe.",
        OutputArea.TRIMMED),
    OPTIMIZE_VIDEO(ToolSection.VIDEO, "Lossless video optimizer", "Repackage for fast start; quality untouched",
        "Copies the existing video and audio streams bit-for-bit into a clean MP4 with the index at the front (plays and uploads faster). This is not compression: quality is identical and the size changes only slightly.",
        OutputArea.OPTIMIZED_VIDEO),
    COMPRESS_VIDEO(ToolSection.VIDEO, "Video compressor", "Re-encode to smaller H.264 MP4 files",
        "Re-encodes videos to H.264 + AAC MP4 at the quality you choose. Lower quality gives smaller files.",
        OutputArea.COMPRESSED_VIDEO),
    MERGE_VIDEOS(ToolSection.VIDEO, "Merge videos", "Join clips into one video, in your order",
        "Joins videos end to end. Clips recorded with the same settings are joined without re-encoding (no quality loss); others are converted to a common size and format first.",
        OutputArea.MERGED_VIDEO),
    VIDEO_SPEED(ToolSection.VIDEO, "Speed & timelapse", "Slow motion, fast forward, timelapses",
        "Plays videos from 0.25× to 60× speed. The sound keeps its natural pitch, or can be muted; long recordings become smooth timelapses.",
        OutputArea.SPEED_VIDEO),
    REMOVE_AUDIO(ToolSection.VIDEO, "Remove video audio", "Silent copies with the video untouched",
        "Creates copies of your videos without the sound track. The picture is copied as-is, with no quality loss.",
        OutputArea.NO_AUDIO),

    COMPRESS_IMAGES(ToolSection.IMAGES, "Image compressor", "JPEG or WebP with quality and size limits",
        "Re-encodes photos as JPEG or WebP at the quality you choose, optionally limiting the width. Aspect ratio and orientation are always preserved.",
        OutputArea.COMPRESSED_IMAGES),
    OPTIMIZE_IMAGES(ToolSection.IMAGES, "Lossless image optimizer", "Pixel-identical PNG or lossless WebP",
        "Stores every pixel exactly as it is in an efficiently compressed lossless file. Savings depend on the source and are not guaranteed.",
        OutputArea.COMPRESSED_IMAGES),
    CONVERT_IMAGES(ToolSection.IMAGES, "Convert images", "PNG, JPEG or WebP from most formats",
        "Converts images (HEIC, AVIF, TIFF, BMP, PSD, RAW previews and more) to PNG, JPEG or WebP.",
        OutputArea.CONVERTED),
    MERGE_IMAGES(ToolSection.IMAGES, "Merge images", "Stack, line up or pack images into one PNG",
        "Combines two or more images into a single PNG without scaling or cropping any of them.",
        OutputArea.MERGED),
    STITCH(ToolSection.IMAGES, "Multi-shot stitcher", "Join overlapping photos into a panorama",
        "Finds where your overlapping photos meet, aligns them and blends them into one high-resolution lossless PNG.",
        OutputArea.STITCHED),
    WATERMARK(ToolSection.IMAGES, "Bulk watermark", "Text or logo on every photo in a batch",
        "Adds a text and/or logo watermark to every image, with independent placement for each image shape.",
        OutputArea.WATERMARKED),
    DUPLICATES(ToolSection.IMAGES, "Duplicate finder", "Find copies and similar shots, free space",
        "Scans your photos on this phone for identical copies, re-saved duplicates and near-identical shots, suggests the best one to keep and moves the rest to the trash when you confirm.",
        OutputArea.CLEAN_IMAGES),

    VIDEO_TO_GIF(ToolSection.GIF, "Video → GIF", "Animated GIFs with adaptive colours",
        "Turns videos into animated GIFs with an adaptive colour palette and accurate frame timing.",
        OutputArea.CONVERTED_GIF),
    COMPRESS_GIF(ToolSection.GIF, "GIF compressor", "Smaller GIFs: size, frame rate, colours",
        "Shrinks existing GIFs by reducing their dimensions, frame rate and colour palette.",
        OutputArea.GIFS),
    OPTIMIZE_GIF(ToolSection.GIF, "GIF optimizer", "Re-pack GIFs while keeping every pixel",
        "Re-encodes GIFs more efficiently while keeping every displayed pixel identical.",
        OutputArea.GIFS),

    PDF_TO_IMAGES(ToolSection.DOCUMENTS, "PDF → images", "Every page as a PNG or JPEG",
        "Renders each page of a PDF to an image exactly as it looks on screen.",
        OutputArea.PDF_IMAGES),
    IMAGES_TO_PDF(ToolSection.DOCUMENTS, "Images → PDF", "One A4 page per image, in your order",
        "Builds an A4 PDF with one image per page, in the order you choose.",
        OutputArea.PDF),
    MERGE_PDFS(ToolSection.DOCUMENTS, "Merge PDFs", "Combine PDFs, keeping text and links",
        "Joins PDFs into one document, keeping their original text, vector graphics, links and page sizes.",
        OutputArea.PDF),
    EXTRACT_PDF_PAGES(ToolSection.DOCUMENTS, "Extract PDF pages", "Pick pages into a new PDF or separate files",
        "Choose page numbers or ranges (like 1-3, 7, 10-) and save them as one new PDF or one PDF per page. Pages are copied as they are: text, links and quality are kept.",
        OutputArea.PDF),
    PDF_SCANNER(ToolSection.DOCUMENTS, "PDF scanner", "Camera or gallery pages into a PDF",
        "Captures pages with the camera or adds photos from the gallery and saves them as an A4 PDF.",
        OutputArea.PDF),

    PRINT(ToolSection.PRINT, "Print", "Photos and PDFs on your Wi-Fi printer, no printer app",
        "Prints photos and PDFs straight to a printer on your Wi-Fi — Epson, HP, Canon, Brother and others that support AirPrint, Mopria or IPP Everywhere — without the printer maker's app. Pick the paper size and type, borderless, several photos per sheet, colour or black & white, quality and copies, with a preview of every sheet. The app talks only to the printer on your own network.",
        OutputArea.PDF),

    REMOVE_METADATA(ToolSection.PRIVACY, "Remove metadata", "Strip location, camera and date info",
        "Makes clean copies of photos and videos without GPS location, camera details, dates, comments or hidden thumbnails. Photo pixels and video streams are copied unchanged (no quality loss); orientation and colour profile are kept.",
        OutputArea.CLEAN_IMAGES, OutputArea.CLEAN_VIDEO),
    EXTRACT_AUDIO(ToolSection.PRIVACY, "Extract audio", "Save a video's AAC sound as M4A",
        "Copies the AAC sound track of each video into an M4A audio file without re-encoding.",
        OutputArea.EXTRACTED_AUDIO);

    val outputPath: String get() = videoArea?.let { "${area.displayPath}\n${it.displayPath}" } ?: area.displayPath

    companion object {
        /** Number of tools (the tool stack runs other tools, so it isn't counted). */
        val toolCount: Int get() = entries.count { it != TOOL_STACK }
    }
}
